# Basic setup for fetching data from the facebook api

### Remember to add an active access token below and adjust the parameters and fields if necessary

In [22]:
# must be specified to be able to use methods of package
import sys
sys.path.append('../src') 
# import packages
import pandas as pd
from political_ads.api_request import get_json_response 

# insert your access token here (expires every 2 hours)
access_token = "EAADqFZC76BDMBAGkMJuoegrCYUZAZARmxCB3ykLgZCTlQ5FVE2sqtNNWeCDD0q0EB6Ca1gR0BWbj7lZBxBScSxq71vMaESUQlNjUENzSxJqIUeV5BMAhCORtZAmkMRvAqGSJ7gMtsUAx9Ods4ZCsJjIneBQ9ZCCU7xYmk0Iyh55ApPhKD58dZBGHYsCsbPxbAyLYgouyJsJth75x8uEv6lMaK"
# get_new_access_token: 


# PARAMETERS NECESSARY
ad_type = "POLITICAL_AND_ISSUE_ADS"
ad_reached_countries = ['US', 'DE'] # Facebook delivered the ads in these countries. Provided as ISO country codes.
search_terms = "climate change" # The terms to search for in your query. We treat a blank space as a logical AND and search for both terms and no other operators. The limit of your string is 100 characters or less.
limit = 2000

# FIELDS to specify your results
fields = ["id", "ad_creative_body", "impressions", "delivery_by_region", "demographic_distribution", "funding_entity"]

# see here for more parameters and fields: https://www.facebook.com/ads/library/api/?source=archive-landing-page 

input_url = f"https://graph.facebook.com/v12.0/ads_archive?search_terms={search_terms}&ad_type={ad_type}&ad_reached_countries={ad_reached_countries}&fields={fields}&limit={limit}"

response = get_json_response(input_url, access_token)

data = pd.DataFrame(response["data"])

In [23]:
data

,id,ad_creative_body,impressions,delivery_by_region,demographic_distribution,funding_entity
0,878708576362819,Transport affects climate change and our urban...,{'lower_bound': '1000000'},"[{'percentage': '2.0E-6', 'region': 'JÃ¤mtland ...","[{'percentage': '0.000114', 'age': '55-64', 'g...",European Commission
1,345860090520766,"Climate change, environmental degradation and ...",{'lower_bound': '1000000'},"[{'percentage': '7.0E-6', 'region': 'Hiiu Coun...","[{'percentage': '0.001705', 'age': '25-34', 'g...",European Commission
2,161524832762330,ðŸŒŽ Sierra Club's City Hike-A-Thon is a national...,"{'lower_bound': '1000', 'upper_bound': '1999'}","[{'percentage': '0.789011', 'region': 'Massach...","[{'percentage': '0.006508', 'age': '45-54', 'g...",SIERRA CLUB
3,317427000179234,ðŸŒŽ Sierra Club's City Hike-A-Thon is a national...,"{'lower_bound': '1000', 'upper_bound': '1999'}","[{'percentage': '0.001553', 'region': 'Connect...","[{'percentage': '0.00155', 'age': '18-24', 'ge...",SIERRA CLUB
4,1033393710740228,ðŸŒŽ Sierra Club's City Hike-A-Thon is a national...,"{'lower_bound': '1000', 'upper_bound': '1999'}","[{'percentage': '0.003442', 'region': 'Connect...","[{'percentage': '0.001724', 'age': '35-44', 'g...",SIERRA CLUB
...,...,...,...,...,...,...
1995,290551399198889,Rep. Cuellar: We have a once-in-a-generation c...,"{'lower_bound': '10000', 'upper_bound': '14999'}","[{'percentage': '1', 'region': 'Texas'}]","[{'percentage': '0.000187', 'age': '65+', 'gen...",Green New Deal Network
1996,2935146080132550,Overwhelmed by climate change? We've got your ...,"{'lower_bound': '0', 'upper_bound': '999'}",NaN,NaN,The Years Project
1997,1584510788557361,"Right now, communities across the nation are b...","{'lower_bound': '35000', 'upper_bound': '39999'}","[{'percentage': '1', 'region': 'Florida'}]","[{'percentage': '0.00272', 'age': '35-44', 'ge...",Green New Deal Network
1998,1007600173421417,Climate change is real. We must combat its adv...,"{'lower_bound': '9000', 'upper_bound': '9999'}","[{'percentage': '1', 'region': 'Florida'}]","[{'percentage': '0.008398', 'age': '35-44', 'g...","SHEILA CHERFILUS MCCORMICK FOR CONGRESS, INC"
1999,1002092720359769,Learn why Colorado Working Families Party supp...,"{'lower_bound': '1000', 'upper_bound': '1999'}","[{'percentage': '1', 'region': 'Colorado'}]","[{'percentage': '0.002584', 'age': '45-54', 'g...",Dan for Boulder Council

In [24]:
paging1 = response["paging"]["next"]

In [25]:
response1 = get_json_response(paging1, access_token)

data1 = pd.DataFrame(response1["data"])

data1

,id,ad_creative_body,impressions,delivery_by_region,demographic_distribution,funding_entity
0,598261591195643,Find out why Colorado Working Families Party s...,"{'lower_bound': '3000', 'upper_bound': '3999'}","[{'percentage': '1', 'region': 'Colorado'}]","[{'percentage': '0.00083', 'age': '65+', 'gend...",Dan for Boulder Council
1,268817805246366,Wildfires. Drought. Poor air quality. Colorada...,"{'lower_bound': '45000', 'upper_bound': '49999'}","[{'percentage': '1', 'region': 'Colorado'}]","[{'percentage': '0.003058', 'age': '35-44', 'g...",Colorado People's Alliance
2,894427081476643,The Denver-metro area broke records with more ...,"{'lower_bound': '100000', 'upper_bound': '1249...","[{'percentage': '1', 'region': 'Colorado'}]","[{'percentage': '0.00167', 'age': '65+', 'gend...",Colorado People's Alliance
3,962713314276445,"Please Mark 12:00 Noon on October 10, 2021 on ...","{'lower_bound': '0', 'upper_bound': '999'}",NaN,NaN,NaN
4,400084224843661,We can protect care workers on the frontlines ...,"{'lower_bound': '0', 'upper_bound': '999'}",NaN,NaN,NRDC Action Fund
...,...,...,...,...,...,...
1995,177027521221877,Find out why scientists agree that climate cha...,"{'lower_bound': '2000', 'upper_bound': '2999'}","[{'percentage': '0.002544', 'region': 'Califor...","[{'percentage': '0.0011', 'age': '25-34', 'gen...",Potential Energy Coalition Inc
1996,182627357290589,Find out why climate scientists agree that cli...,"{'lower_bound': '4000', 'upper_bound': '4999'}","[{'percentage': '0.000221', 'region': 'Alabama...","[{'percentage': '0.001357', 'age': '55-64', 'g...",Potential Energy Coalition Inc
1997,441533627207474,Find out why climate scientists agree that cli...,"{'lower_bound': '2000', 'upper_bound': '2999'}","[{'percentage': '0.000478', 'region': 'Alabama...","[{'percentage': '0.000472', 'age': '25-34', 'g...",Potential Energy Coalition Inc
1998,1882905298549446,Find out why scientists agree that climate cha...,"{'lower_bound': '10000', 'upper_bound': '14999'}","[{'percentage': '0.00017', 'region': 'Alabama'...","[{'percentage': '0.000428', 'age': '65+', 'gen...",Potential Energy Coalition Inc
1999,2918763558389867,Find out why scientists agree that climate cha...,"{'lower_bound': '1000', 'upper_bound': '1999'}","[{'percentage': '0.000627', 'region': 'Alaska'...","[{'percentage': '0.001883', 'age': '35-44', 'g...",Potential Energy Coalition Inc

In [29]:
import time 

#https://developers.facebook.com/docs/graph-api/results


counter = 0
for i in range(10):

    paging = response["paging"]["next"]
    next_response = get_json_response(paging, access_token)

    new_page = pd.DataFrame(next_response['data'])
    data = data.append(new_page, ignore_index=True)
    time.sleep(10)
    counter+=1
    print(counter)


data.count() #Should show 600

1
2
3
4
5
6
7
8
9
10

id                          28000
ad_creative_body            27761
impressions                 28000
delivery_by_region          21642
demographic_distribution    21642
funding_entity              26085
dtype: int64

In [27]:
data.describe()

,id,ad_creative_body,impressions,delivery_by_region,demographic_distribution,funding_entity
count,8000,7941,8000,6112,6112,7385
unique,4000,1076,38,2281,3007,402
top,598261591195643,Opening up the Arctic National Wildlife Refuge...,"{'lower_bound': '0', 'upper_bound': '999'}","[{'percentage': '1', 'region': 'California'}]","[{'percentage': '0.012702', 'age': '25-34', 'g...",NRDC Action Fund
freq,3,252,4365,212,3,519

In [28]:
data.loc[[0]]["delivery_by_region"]

0    [{'percentage': '2.0E-6', 'region': 'JÃ¤mtland ...
Name: delivery_by_region, dtype: object